CREATE TABLE "wp_honeypot_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wp_honeypot_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"frontend" varchar(80) DEFAULT 'portfolio' NOT NULL,
	"method" varchar(12) NOT NULL,
	"path" text NOT NULL,
	"query_string" text,
	"step" varchar(24),
	"route_state" varchar(48) NOT NULL,
	"status_code" integer NOT NULL,
	"ip_address" varchar(160),
	"user_agent" text,
	"referer" text,
	"accept_language" text,
	"content_type" text,
	"raw_body" text,
	"payload" jsonb NOT NULL
);
--> statement-breakpoint
CREATE INDEX "wp_honeypot_logs_frontend_created_at_idx" ON "wp_honeypot_logs" USING btree ("frontend","created_at");--> statement-breakpoint
CREATE INDEX "wp_honeypot_logs_ip_created_at_idx" ON "wp_honeypot_logs" USING btree ("ip_address","created_at");