CREATE TYPE "public"."content_entity_type" AS ENUM('blog_post', 'company', 'experience', 'project', 'skill');--> statement-breakpoint
CREATE TABLE "blog_post_mentions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blog_post_mentions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blog_post_revision_id" integer NOT NULL,
	"mentioned_entity_id" integer NOT NULL,
	"source_block_id" varchar(120),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content_entities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "content_entities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" "content_entity_type" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "blog_posts" ADD COLUMN "entity_id" integer;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "entity_id" integer;--> statement-breakpoint
ALTER TABLE "experience" ADD COLUMN "entity_id" integer;--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "entity_id" integer;--> statement-breakpoint
ALTER TABLE "skills" ADD COLUMN "entity_id" integer;--> statement-breakpoint
DO $$
DECLARE
	source_row record;
	new_entity_id integer;
BEGIN
	FOR source_row IN SELECT "id" FROM "blog_posts" ORDER BY "id" LOOP
		INSERT INTO "content_entities" ("type") VALUES ('blog_post') RETURNING "id" INTO new_entity_id;
		UPDATE "blog_posts" SET "entity_id" = new_entity_id WHERE "id" = source_row."id";
	END LOOP;

	FOR source_row IN SELECT "id" FROM "companies" ORDER BY "id" LOOP
		INSERT INTO "content_entities" ("type") VALUES ('company') RETURNING "id" INTO new_entity_id;
		UPDATE "companies" SET "entity_id" = new_entity_id WHERE "id" = source_row."id";
	END LOOP;

	FOR source_row IN SELECT "id" FROM "experience" ORDER BY "id" LOOP
		INSERT INTO "content_entities" ("type") VALUES ('experience') RETURNING "id" INTO new_entity_id;
		UPDATE "experience" SET "entity_id" = new_entity_id WHERE "id" = source_row."id";
	END LOOP;

	FOR source_row IN SELECT "id" FROM "projects" ORDER BY "id" LOOP
		INSERT INTO "content_entities" ("type") VALUES ('project') RETURNING "id" INTO new_entity_id;
		UPDATE "projects" SET "entity_id" = new_entity_id WHERE "id" = source_row."id";
	END LOOP;

	FOR source_row IN SELECT "id" FROM "skills" ORDER BY "id" LOOP
		INSERT INTO "content_entities" ("type") VALUES ('skill') RETURNING "id" INTO new_entity_id;
		UPDATE "skills" SET "entity_id" = new_entity_id WHERE "id" = source_row."id";
	END LOOP;
END $$;--> statement-breakpoint
ALTER TABLE "blog_posts" ALTER COLUMN "entity_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "companies" ALTER COLUMN "entity_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "experience" ALTER COLUMN "entity_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "entity_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "skills" ALTER COLUMN "entity_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "blog_post_mentions" ADD CONSTRAINT "blog_post_mentions_blog_post_revision_id_blog_post_revisions_id_fk" FOREIGN KEY ("blog_post_revision_id") REFERENCES "public"."blog_post_revisions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blog_post_mentions" ADD CONSTRAINT "blog_post_mentions_mentioned_entity_id_content_entities_id_fk" FOREIGN KEY ("mentioned_entity_id") REFERENCES "public"."content_entities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "blog_post_mentions_revision_id_idx" ON "blog_post_mentions" USING btree ("blog_post_revision_id");--> statement-breakpoint
CREATE INDEX "blog_post_mentions_entity_id_idx" ON "blog_post_mentions" USING btree ("mentioned_entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "blog_post_mentions_revision_entity_idx" ON "blog_post_mentions" USING btree ("blog_post_revision_id","mentioned_entity_id");--> statement-breakpoint
CREATE INDEX "content_entities_type_idx" ON "content_entities" USING btree ("type");--> statement-breakpoint
ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_entity_id_content_entities_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."content_entities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "companies" ADD CONSTRAINT "companies_entity_id_content_entities_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."content_entities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "experience" ADD CONSTRAINT "experience_entity_id_content_entities_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."content_entities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_entity_id_content_entities_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."content_entities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "skills" ADD CONSTRAINT "skills_entity_id_content_entities_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."content_entities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "blog_posts_entity_id_idx" ON "blog_posts" USING btree ("entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "companies_entity_id_idx" ON "companies" USING btree ("entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "experience_entity_id_idx" ON "experience" USING btree ("entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "projects_entity_id_idx" ON "projects" USING btree ("entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "skills_entity_id_idx" ON "skills" USING btree ("entity_id");
